In [51]:
import soundfile as sf

# Leggi il file WAV
data, sample_rate = sf.read('/home/gzanin/Downloads/01-A1-241121_1152.wav')

print(len(data), sample_rate)


6709604 44100


In [15]:
import soundfile as sf

# Leggi il file WAV
data, sample_rate = sf.read('/home/gzanin/Downloads/05-O5-241120_1008(1).wav')

print(len(data), sample_rate)
print(data)

1844580 48000
[-0.00216043 -0.00216413 -0.00217211 ... -0.00231469 -0.00232518
 -0.00234926]


In [17]:
%pip install h5py

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 1.6 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [18]:
import h5py

with h5py.File('/home/gzanin/Downloads/6dof_SRIRs_zylia_SH/6DoF_SRIRs_zylia_SH_0percent_absorbers_enabled.sofa', 'r') as sofa_file:
    print(list(sofa_file.keys()))

['I', 'C', 'R', 'E', 'N', 'M', 'S', 'ListenerPosition', 'ReceiverPosition', 'SourcePosition', 'EmitterPosition', 'ListenerUp', 'ListenerView', 'SourceUp', 'SourceView', 'Data.IR', 'Data.SamplingRate', 'Data.Delay']


In [22]:
sofa_file['ListenerPosition']

KeyError: 'Unable to synchronously open object (invalid identifier type to function)'

In [24]:
%pip install netCDF4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 1.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 2.5 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [67]:
from netCDF4 import Dataset

# Specifica il percorso al file
file_path = '/home/gzanin/Downloads/6dof_SRIRs_zylia_SH/6DoF_SRIRs_zylia_SH_0percent_absorbers_enabled.sofa'

# Carica il file
data = Dataset(file_path, mode='r')

# Visualizza tutte le chiavi disponibili
print("Chiavi disponibili nel file:")
print(list(data.variables.keys()))

# Accesso a una specifica chiave
listener_position = data.variables['ListenerPosition'][:]
print("Listener Position:", listener_position)

# Accesso a una specifica chiave
receiver_position = data.variables['ReceiverPosition'][:]
print("Receiver Position:", receiver_position)

# Accesso a una specifica chiave
Source_position = data.variables['SourcePosition'][:]
print("Source Position:", Source_position)

# Accesso a una specifica chiave
emitter_position = data.variables['EmitterPosition'][:]
print("Emitter Position:", emitter_position)

# Accesso a una specifica chiave
listener_up = data.variables['ListenerUp'][:]
print("Listener Up:", listener_up)

# Accesso a una specifica chiave
listener_view = data.variables['ListenerView'][:]
print("Listener View:", listener_view)

# Accesso a una specifica chiave
source_up = data.variables['SourceUp'][:]
print("Source Up:", source_up)

# Accesso a una specifica chiave
source_view = data.variables['SourceView'][:]
print("Source View:", source_view)

# Accesso a una specifica chiave
IRs = data.variables['Data.IR'][:]
print("'Data.IR':", IRs)

# Accesso a una specifica chiave
sampling_rate = data.variables['Data.SamplingRate'][:]
print("'Data.SamplingRate':", sampling_rate)

# Accesso a una specifica chiave
delay = data.variables['Data.Delay'][:]
print("'Data.Delay':", delay)

Chiavi disponibili nel file:
['ListenerPosition', 'ReceiverPosition', 'SourcePosition', 'EmitterPosition', 'ListenerUp', 'ListenerView', 'SourceUp', 'SourceView', 'Data.IR', 'Data.SamplingRate', 'Data.Delay']
Listener Position: [[6.37  1.3   1.55 ]
 [6.37  1.3   1.55 ]
 [6.37  1.3   1.55 ]
 [5.12  1.3   1.55 ]
 [5.12  1.3   1.55 ]
 [5.12  1.3   1.55 ]
 [3.87  1.3   1.55 ]
 [3.87  1.3   1.55 ]
 [3.87  1.3   1.55 ]
 [2.62  1.3   1.55 ]
 [2.62  1.3   1.55 ]
 [2.62  1.3   1.55 ]
 [1.37  1.3   1.55 ]
 [1.37  1.3   1.55 ]
 [1.37  1.3   1.55 ]
 [5.12  4.745 1.55 ]
 [5.12  4.745 1.55 ]
 [5.12  4.745 1.55 ]
 [2.62  4.745 1.55 ]
 [2.62  4.745 1.55 ]
 [2.62  4.745 1.55 ]]
Receiver Position: [[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.

In [68]:
IRs.shape

(21, 16, 120000)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

for i in IRs:
    print(max([max(j**2) for j in i]))
    '''
    N_fft = 120000  # FFT length
    print(np.average(np.abs(np.fft.fft(i[0], axis=0, n=N_fft))))
    '''
    plt.plot(i[0])
    plt.show()
    

In [69]:
IRs.shape

(21, 16, 120000)

In [4]:
import numpy as np

In [82]:
m = []

s2_indexes = [1,4,7,10,13,16,19]
for n in s2_indexes:
    m.append(IRs[n][0])

m = np.array(m)

In [83]:
np.save('/home/gzanin/Desktop/espoo_S2/RIRs.npy', m)

In [78]:
#7 omnidirectionals
m.shape

(7, 120000)

In [20]:
# Specifica il percorso al file
file_path = '/home/gzanin/Downloads/6dof_SRIRs_zylia_raw/6DoF_SRIRs_zylia_raw_100percent_absorbers_enabled.sofa'

# Carica il file
data = Dataset(file_path, mode='r')
IRs = data.variables['Data.IR'][:]
capsules_signals = np.array(IRs[10])

print(capsules_signals.shape)

np.save('../A_espoo_S2_R4_absorb.npy', capsules_signals.T)


(19, 120000)


In [38]:
# Specifica il percorso al file
file_path = '/home/gzanin/Downloads/6dof_SRIRs_zylia_SH/6DoF_SRIRs_zylia_SH_0percent_absorbers_enabled.sofa'

# Carica il file
data = Dataset(file_path, mode='r')
IRs = data.variables['Data.IR'][:]
sh_signals = np.array(IRs[19])

print(sh_signals.shape)

np.save('../B_espoo_S2_R7.npy', sh_signals.T)  # Save the B format file (it's a complex)

(16, 120000)


In [60]:
#up, sampling_rate = sf.read('/home/gzanin/Desktop/espoo_s2_r1_090.wav')
up = np.load('../espoo_s2_r1_090.npy', allow_pickle=True, encoding= 'latin1')
down = np.load('../espoo_s2_r1_0-90.npy', allow_pickle=True, encoding= 'latin1')
dx = np.load('../espoo_s2_r1_900.npy', allow_pickle=True, encoding= 'latin1')
sx = np.load('../espoo_s2_r1_2700.npy', allow_pickle=True, encoding= 'latin1')
forward = np.load('../espoo_s2_r1_00.npy', allow_pickle=True, encoding= 'latin1')
behind = np.load('../espoo_s2_r1_1800.npy', allow_pickle=True, encoding= 'latin1')

In [84]:
##########only 12 microphones are considered
import render_optimized as render
n = []

#up-down, dx-sx and forward-behind
azimuths = [0,0,90, 270, 0, 180]
elevations = [90, -90, 0,0,0,0]

for i in range (7):
    n.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(n)):
    n[j][0]['t_response'] = np.load('../espoo_s2_r'+str(j+1)+'_090.npy', allow_pickle=True, encoding= 'latin1')
    n[j][1]['t_response'] = np.load('../espoo_s2_r'+str(j+1)+'_0-90.npy', allow_pickle=True, encoding= 'latin1')
    n[j][2]['t_response'] = np.load('../espoo_s2_r'+str(j+1)+'_900.npy', allow_pickle=True, encoding= 'latin1')
    n[j][3]['t_response'] = np.load('../espoo_s2_r'+str(j+1)+'_2700.npy', allow_pickle=True, encoding= 'latin1')
    n[j][4]['t_response'] = np.load('../espoo_s2_r'+str(j+1)+'_00.npy', allow_pickle=True, encoding= 'latin1')
    n[j][5]['t_response'] = np.load('../espoo_s2_r'+str(j+1)+'_1800.npy', allow_pickle=True, encoding= 'latin1')

n = np.array(n)

In [80]:
n.shape

(7, 6)

In [86]:
np.save('/home/gzanin/Desktop/espoo_S2_amb/RIRs.npy', n)

In [87]:
espoo_xyzs = np.array([[6.37, 1.3, 1.55], [5.12, 1.3, 1.55], [3.87, 1.3, 1.55], [2.62, 1.3, 1.55], [1.37, 1.3, 1.55],[5.12, 4.745, 1.55 ],[2.62, 4.745, 1.55]])

In [88]:
np.save('/home/gzanin/Desktop/espoo_S2_amb/xyzs.npy', espoo_xyzs)
np.save('/home/gzanin/Desktop/espoo_S2/xyzs.npy', espoo_xyzs)

In [90]:
np.save('/home/gzanin/Desktop/espoo_S2_amb/music.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/music.npy', np.array([]))

np.save('/home/gzanin/Desktop/espoo_S2_amb/music_dls.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/music_dls.npy', np.array([]))

np.save('/home/gzanin/Desktop/espoo_S2_amb/bin_music.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/bin_music.npy', np.array([]))

np.save('/home/gzanin/Desktop/espoo_S2_amb/bin_music_dls.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/bin_music_dls.npy', np.array([]))

np.save('/home/gzanin/Desktop/espoo_S2_amb/bin_xyzs.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/bin_xyzs.npy', np.array([]))

np.save('/home/gzanin/Desktop/espoo_S2_amb/bin_RIRs.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/bin_RIRs.npy', np.array([]))

np.save('/home/gzanin/Desktop/espoo_S2_amb/bin_music.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/bin_music.npy', np.array([]))

np.save('/home/gzanin/Desktop/espoo_S2_amb/mic_numbers.npy', np.array([]))
np.save('/home/gzanin/Desktop/espoo_S2/mic_numbers.npy', np.array([]))