In [1]:
import numpy as np
import torch

In [2]:
#data = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', allow_pickle = True)

data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']


OrderedDict([('energy_vector',
              tensor([[[-1.5401, -0.7943, -0.9091, -1.3150, -0.6574, -0.3863, -1.1271,
                        -1.1646, -0.8094, -1.3051],
                       [ 1.5401,  0.7943,  0.9091,  1.3150,  0.6574,  0.3863,  1.1271,
                         1.1646,  0.8094,  1.3051]],
              
                      [[-0.9759, -0.4994, -1.3032, -1.2177, -0.3614, -0.9981, -1.0377,
                        -0.7199, -0.8342, -1.6437],
                       [ 0.9759,  0.4994,  1.3032,  1.2177,  0.3614,  0.9981,  1.0377,
                         0.7199,  0.8342,  1.6437]],
              
                      [[-2.0089, -1.5780, -1.4189, -1.0632, -1.5322, -0.0126, -0.3368,
                        -0.2425,  0.1932, -0.5778],
                       [ 2.0089,  1.5780,  1.4189,  1.0632,  1.5322,  0.0126,  0.3368,
                         0.2425, -0.1932,  0.5778]],
              
                      [[-1.7584, -0.9833, -1.3878, -2.1214, -2.0416, -0.6179, -1.1845,


In [3]:
data['model_state_dict']['spline_values']

tensor([-1.0309, -0.4218, -1.0556,  1.0760,  1.2255, -0.1364, -0.5142, -1.3442,
        -0.0597, -0.5715, -0.3542, -0.6326,  1.4924,  2.8066,  3.5737,  3.5931,
         3.7868,  4.3739,  1.1239,  3.6809,  4.4836,  4.8477,  4.7484,  4.6311,
         3.7861,  5.8187,  4.7990,  2.5141,  3.6256,  3.8223,  4.3824,  3.4411,
         3.2556,  3.3974])

In [4]:
model_weights = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/hallwayBase/weights.pt', map_location=torch.device('cpu'))

#print(model_weights.keys())

In [5]:
model_weights['model_state_dict']['spline_values']

tensor([-1.1889,  0.9600,  0.1497, -1.6674, -1.7362, -0.8662, -0.0920, -0.1603,
        -0.7774, -0.5799, -0.2962, -0.4480, -0.3558, -0.4179, -0.6262, -0.7645,
        -0.8553, -0.9175, -1.0549, -1.1494, -1.2660, -1.3254, -1.3975, -1.4152,
        -1.5259, -1.5676, -1.6296, -1.7462, -1.7349, -1.8844, -2.0238, -2.2500,
        -2.5868, -2.5822])

In [4]:
data_losses = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/losses.npy')
data_losses.shape

print("epochs made:", data_losses.shape[0]/8)

epochs made: 263.0


Create dummy dataset

In [11]:
import fibonacci_utilities as fib
import render

In [12]:
azimuths, elevations = fib.fibonacci_azimuths_and_elevations(15)

In [ ]:
data = np.load('/home/gzanin/Desktop/classroomBase/RIRs.npy', allow_pickle=True, encoding= 'latin1')
data.shape

In [20]:
##########only 12 microphones are considered

m = []

for i in range (12):
    m.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(m)):
    for r in m[j]:
        r['t_response'] = data[j]

m = np.array(m)

In [23]:
#m = data[:12]

In [ ]:
m.shape

In [24]:
np.save('/home/gzanin/Desktop/prova_dataset/RIRs.npy', m)

In [ ]:
new_data = np.load('/home/gzanin/Desktop/prova_dataset/xyzs.npy', allow_pickle=True, encoding= 'latin1')

new_data
