In [2]:
import numpy as np
import torch

In [5]:
#data = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', allow_pickle = True)

data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_different/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']


OrderedDict([('energy_vector',
              tensor([[[ 0.2358, -0.3700,  1.2930, -0.3559, -0.5278, -0.4747, -1.1789,
                        -2.0230, -1.1184, -1.3833],
                       [-0.2358,  0.3700, -1.2930,  0.3559,  0.5278,  0.4747,  1.1789,
                         2.0230,  1.1184,  1.3833]],
              
                      [[-1.1596, -0.4881, -0.3753, -1.7862,  0.4012, -1.7094, -1.6006,
                        -2.0352,  0.8716,  1.9510],
                       [ 1.1596,  0.4881,  0.3753,  1.7862, -0.4012,  1.7094,  1.6006,
                         2.0352, -0.8716, -1.9510]],
              
                      [[-2.4367, -1.0749, -1.5681, -0.6310, -0.5543, -1.6173, -0.8984,
                        -1.0310, -2.3357, -1.9602],
                       [ 2.4367,  1.0749,  1.5681,  0.6310,  0.5543,  1.6173,  0.8984,
                         1.0310,  2.3357,  1.9602]],
              
                      [[-1.6467, -0.4605, -1.1996, -1.1455, -1.5221, -0.6231, -1.6541,


In [6]:
data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/classroomBase/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']

OrderedDict([('energy_vector',
              tensor([[[-0.5305, -0.4278, -0.2579, -0.3598, -1.6096, -0.7284, -1.8826,
                        -1.6226, -1.5753, -1.9941],
                       [ 0.5305,  0.4278,  0.2579,  0.3598,  1.6096,  0.7284,  1.8826,
                         1.6226,  1.5753,  1.9941]],
              
                      [[-2.4384,  0.8858, -0.2965, -1.5742, -0.2930, -1.9829, -1.7962,
                        -1.9131, -0.0154,  0.2472],
                       [ 2.4384, -0.8858,  0.2965,  1.5742,  0.2930,  1.9829,  1.7962,
                         1.9131,  0.0154, -0.2472]],
              
                      [[-0.9421, -0.6755, -3.6006, -0.7103, -0.8803, -1.3149, -2.2866,
                        -2.6399, -2.8685, -2.1082],
                       [ 0.9421,  0.6755,  3.6006,  0.7103,  0.8803,  1.3149,  2.2866,
                         2.6399,  2.8685,  2.1082]],
              
                      [[-4.0914, -2.7232, -0.8506, -2.3887, -3.6858, -1.3391, -2.6380,


In [3]:
data['model_state_dict']['spline_values']

tensor([-0.6144, -0.1386, -0.8911,  1.4687,  1.6805,  0.0834, -0.0577, -0.9298,
         0.3006, -0.1819, -0.2970, -0.4653,  1.9687,  3.3043,  3.9816,  3.9033,
         3.7904,  4.3551,  1.2830,  4.0281,  4.7798,  5.2476,  4.9928,  4.7315,
         3.8250,  5.9038,  4.6655,  2.5565,  3.7240,  3.9094,  4.4227,  3.3289,
         3.0696,  3.1734])

In [4]:
model_weights = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/hallwayBase/weights.pt', map_location=torch.device('cpu'))

#print(model_weights.keys())

In [5]:
model_weights['model_state_dict']['spline_values']

tensor([-1.1889,  0.9600,  0.1497, -1.6674, -1.7362, -0.8662, -0.0920, -0.1603,
        -0.7774, -0.5799, -0.2962, -0.4480, -0.3558, -0.4179, -0.6262, -0.7645,
        -0.8553, -0.9175, -1.0549, -1.1494, -1.2660, -1.3254, -1.3975, -1.4152,
        -1.5259, -1.5676, -1.6296, -1.7462, -1.7349, -1.8844, -2.0238, -2.2500,
        -2.5868, -2.5822])

In [6]:
data_losses = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/losses.npy')
data_losses.shape

print("epochs made:", data_losses.shape[0]/8)

epochs made: 301.0


Create dummy dataset

In [11]:
import fibonacci_utilities as fib
import render

In [12]:
azimuths, elevations = fib.fibonacci_azimuths_and_elevations(15)

In [ ]:
data = np.load('/home/gzanin/Desktop/classroomBase/RIRs.npy', allow_pickle=True, encoding= 'latin1')
data.shape

In [20]:
##########only 12 microphones are considered

m = []

for i in range (12):
    m.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(m)):
    for r in m[j]:
        r['t_response'] = data[j]

m = np.array(m)

In [23]:
#m = data[:12]

In [ ]:
m.shape

In [24]:
np.save('/home/gzanin/Desktop/prova_dataset/RIRs.npy', m)

In [ ]:
new_data = np.load('/home/gzanin/Desktop/prova_dataset/xyzs.npy', allow_pickle=True, encoding= 'latin1')

new_data
