In [2]:
import numpy as np
import torch

In [2]:
#data = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', allow_pickle = True)

data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']


OrderedDict([('energy_vector',
              tensor([[[-1.4181, -0.7319, -0.8180, -1.2595, -0.6004, -0.4023, -1.1022,
                        -1.2090, -0.7921, -1.2131],
                       [ 1.4181,  0.7319,  0.8180,  1.2595,  0.6004,  0.4023,  1.1022,
                         1.2090,  0.7921,  1.2131]],
              
                      [[-0.9758, -0.5013, -1.2749, -1.0446, -0.4070, -1.0256, -0.8352,
                        -0.5703, -0.7295, -1.4489],
                       [ 0.9758,  0.5013,  1.2749,  1.0446,  0.4070,  1.0256,  0.8352,
                         0.5703,  0.7295,  1.4489]],
              
                      [[-1.8832, -1.4464, -1.4775, -1.1178, -1.4811, -0.1710, -0.4940,
                        -0.4712,  0.0776, -0.5494],
                       [ 1.8832,  1.4464,  1.4775,  1.1178,  1.4811,  0.1710,  0.4940,
                         0.4712, -0.0776,  0.5494]],
              
                      [[-1.6162, -0.9132, -1.2496, -2.0956, -1.9076, -0.6826, -1.2030,


In [3]:
data['model_state_dict']['spline_values']

tensor([-1.4584, -0.8253, -1.2196,  0.4358,  0.5591, -0.2744, -0.8465, -1.6628,
        -0.5773, -1.1724, -0.5567, -0.7167,  1.0462,  2.2586,  3.0895,  3.2626,
         3.5813,  4.0390,  1.0101,  3.3931,  4.1651,  4.4641,  4.5458,  4.4525,
         3.7744,  5.6220,  4.9598,  2.5068,  3.5196,  3.7540,  4.3187,  3.5400,
         3.4195,  3.6077])

In [4]:
model_weights = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/hallwayBase/weights.pt', map_location=torch.device('cpu'))

#print(model_weights.keys())

In [5]:
model_weights['model_state_dict']['spline_values']

tensor([-1.1889,  0.9600,  0.1497, -1.6674, -1.7362, -0.8662, -0.0920, -0.1603,
        -0.7774, -0.5799, -0.2962, -0.4480, -0.3558, -0.4179, -0.6262, -0.7645,
        -0.8553, -0.9175, -1.0549, -1.1494, -1.2660, -1.3254, -1.3975, -1.4152,
        -1.5259, -1.5676, -1.6296, -1.7462, -1.7349, -1.8844, -2.0238, -2.2500,
        -2.5868, -2.5822])

In [6]:
data_losses = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/losses.npy')
data_losses.shape

print("epochs made:", data_losses.shape[0]/8)

epochs made: 226.0


Create dummy dataset

In [11]:
import fibonacci_utilities as fib
import render

In [12]:
azimuths, elevations = fib.fibonacci_azimuths_and_elevations(15)

In [ ]:
data = np.load('/home/gzanin/Desktop/classroomBase/RIRs.npy', allow_pickle=True, encoding= 'latin1')
data.shape

In [20]:
##########only 12 microphones are considered

m = []

for i in range (12):
    m.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(m)):
    for r in m[j]:
        r['t_response'] = data[j]

m = np.array(m)

In [23]:
#m = data[:12]

In [ ]:
m.shape

In [24]:
np.save('/home/gzanin/Desktop/prova_dataset/RIRs.npy', m)

In [ ]:
new_data = np.load('/home/gzanin/Desktop/prova_dataset/xyzs.npy', allow_pickle=True, encoding= 'latin1')

new_data
