In [4]:
import numpy as np
import torch

In [7]:
#data = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', allow_pickle = True)

data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']


OrderedDict([('energy_vector',
              tensor([[[-0.3652, -0.4663, -0.4409, -0.5159, -0.3000, -0.1640,  0.0396,
                        -0.0046,  0.0875, -0.3347],
                       [ 0.3652,  0.4663,  0.4409,  0.5159,  0.3000,  0.1640, -0.0396,
                         0.0046, -0.0875,  0.3347]],
              
                      [[-0.2893, -0.5098, -0.3838, -0.4227, -0.3012, -0.3415, -0.1468,
                        -0.1169, -0.1215, -0.3729],
                       [ 0.2893,  0.5098,  0.3838,  0.4227,  0.3012,  0.3415,  0.1468,
                         0.1169,  0.1215,  0.3729]],
              
                      [[-0.4133, -0.5344, -0.5600, -0.4911, -0.3714, -0.2711, -0.2683,
                        -0.2164,  0.0027, -0.3472],
                       [ 0.4133,  0.5344,  0.5600,  0.4911,  0.3714,  0.2711,  0.2683,
                         0.2164, -0.0027,  0.3472]],
              
                      [[-0.4157, -0.5086, -0.5342, -0.5445, -0.3857, -0.3250, -0.4351,


In [8]:
data['model_state_dict']['spline_values']

tensor([-4.2044, -3.9225, -4.0867, -3.3843, -3.0853, -2.9088, -2.9768, -3.2648,
        -2.7226, -3.0500, -2.7532, -2.4338, -1.9918, -0.9606, -0.0437,  0.2916,
         0.5230,  0.9110,  0.4990,  1.2634,  1.5919,  1.8620,  2.1397,  2.3796,
         2.6492,  3.0589,  3.4697,  3.0509,  3.5037,  3.8132,  4.2818,  4.2243,
         4.4209,  4.7026])

In [12]:
model_weights = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/hallwayBase/weights.pt', map_location=torch.device('cpu'))

#print(model_weights.keys())

In [13]:
model_weights['model_state_dict']['spline_values']

tensor([-1.1889,  0.9600,  0.1497, -1.6674, -1.7362, -0.8662, -0.0920, -0.1603,
        -0.7774, -0.5799, -0.2962, -0.4480, -0.3558, -0.4179, -0.6262, -0.7645,
        -0.8553, -0.9175, -1.0549, -1.1494, -1.2660, -1.3254, -1.3975, -1.4152,
        -1.5259, -1.5676, -1.6296, -1.7462, -1.7349, -1.8844, -2.0238, -2.2500,
        -2.5868, -2.5822])

In [9]:
data_losses = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/losses.npy')
data_losses.shape

(320,)

In [10]:
data_losses = np.load('/home/gzanin/Desktop/prova_training_2epochs/losses.npy')
data_losses.shape

(16,)

Create dummy dataset

In [11]:
import fibonacci_utilities as fib
import render

In [5]:
def initialize_directional_list_for_beampattern(angular_sensitivity, n_freq_samples, device):

    frequency_responses_list = []
    used_angle = 180/(int(180/angular_sensitivity))
    azimuths = np.arange(0, 360, used_angle)
    elevations = np.arange(-90, 90+ used_angle, used_angle)
    for elevation in elevations:
        if (elevation == -90 or elevation == 90):
            direction_dict = dict()
            direction_dict['angle'] = [0, elevation]#-90 and +90 elevations are considered having azimuth=0
            direction_dict['f_response'] = torch.zeros(n_freq_samples).to(device)
            frequency_responses_list.append(direction_dict)
        else:   
            for azimuth in azimuths:
                direction_dict = dict()
                direction_dict['angle'] = [azimuth, elevation]
                direction_dict['f_response'] = torch.zeros(n_freq_samples).to(device)
                frequency_responses_list.append(direction_dict)

    return frequency_responses_list

In [12]:
azimuths, elevations = fib.fibonacci_azimuths_and_elevations(15)

In [16]:
data = np.load('/home/gzanin/Desktop/classroomBase/RIRs.npy', allow_pickle=True, encoding= 'latin1')
data.shape

(630, 671884)

In [20]:
##########only 12 microphones are considered

m = []

for i in range (12):
    m.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(m)):
    for r in m[j]:
        r['t_response'] = data[j]

m = np.array(m)

In [23]:
#m = data[:12]

In [21]:
m.shape

(12, 15)

In [24]:
np.save('/home/gzanin/Desktop/prova_dataset/RIRs.npy', m)

In [25]:
new_data = np.load('/home/gzanin/Desktop/prova_dataset/RIRs.npy', allow_pickle=True, encoding= 'latin1')

new_data


array([[{'angle': [0.0, 0.0], 'f_response': tensor([0.+0.j]), 't_response': array([ 6.11514818e-06,  7.35741694e-06,  5.00817302e-06, ...,
               -7.26507135e-07,  3.53323294e-07,  5.90716509e-07])}                                                                       ,
        {'angle': [23.9, -20.36], 'f_response': tensor([0.+0.j]), 't_response': array([ 6.11514818e-06,  7.35741694e-06,  5.00817302e-06, ...,
               -7.26507135e-07,  3.53323294e-07,  5.90716509e-07])}                                                                           ,
        {'angle': [-4.9, 44.2], 'f_response': tensor([0.+0.j]), 't_response': array([ 6.11514818e-06,  7.35741694e-06,  5.00817302e-06, ...,
               -7.26507135e-07,  3.53323294e-07,  5.90716509e-07])}                                                                         ,
        {'angle': [-41.15, -40.64], 'f_response': tensor([0.+0.j]), 't_response': array([ 6.11514818e-06,  7.35741694e-06,  5.00817302e-06, ...,
      