In [1]:
import numpy as np
import torch

In [2]:
#data = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', allow_pickle = True)

data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']


OrderedDict([('energy_vector',
              tensor([[[-1.6225, -0.7819, -0.9241, -1.0965, -0.6052, -0.2993, -1.0732,
                        -1.0307, -0.7379, -1.3821],
                       [ 1.6225,  0.7819,  0.9241,  1.0965,  0.6052,  0.2993,  1.0732,
                         1.0307,  0.7379,  1.3821]],
              
                      [[-0.9106, -0.4159, -1.3413, -1.0573, -0.2784, -1.0093, -1.2336,
                        -0.8712, -0.9405, -1.8466],
                       [ 0.9106,  0.4159,  1.3413,  1.0573,  0.2784,  1.0093,  1.2336,
                         0.8712,  0.9405,  1.8466]],
              
                      [[-2.1117, -1.7155, -1.3066, -1.0594, -1.6962,  0.0512, -0.3373,
                        -0.1897,  0.1828, -0.7508],
                       [ 2.1117,  1.7155,  1.3066,  1.0594,  1.6962, -0.0512,  0.3373,
                         0.1897, -0.1828,  0.7508]],
              
                      [[-1.8291, -0.9968, -1.3955, -2.1800, -2.1157, -0.5392, -1.1801,


In [3]:
data['model_state_dict']['spline_values']

tensor([-0.6144, -0.1386, -0.8911,  1.4687,  1.6805,  0.0834, -0.0577, -0.9298,
         0.3006, -0.1819, -0.2970, -0.4653,  1.9687,  3.3043,  3.9816,  3.9033,
         3.7904,  4.3551,  1.2830,  4.0281,  4.7798,  5.2476,  4.9928,  4.7315,
         3.8250,  5.9038,  4.6655,  2.5565,  3.7240,  3.9094,  4.4227,  3.3289,
         3.0696,  3.1734])

In [4]:
model_weights = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/hallwayBase/weights.pt', map_location=torch.device('cpu'))

#print(model_weights.keys())

In [5]:
model_weights['model_state_dict']['spline_values']

tensor([-1.1889,  0.9600,  0.1497, -1.6674, -1.7362, -0.8662, -0.0920, -0.1603,
        -0.7774, -0.5799, -0.2962, -0.4480, -0.3558, -0.4179, -0.6262, -0.7645,
        -0.8553, -0.9175, -1.0549, -1.1494, -1.2660, -1.3254, -1.3975, -1.4152,
        -1.5259, -1.5676, -1.6296, -1.7462, -1.7349, -1.8844, -2.0238, -2.2500,
        -2.5868, -2.5822])

In [6]:
data_losses = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/losses.npy')
data_losses.shape

print("epochs made:", data_losses.shape[0]/8)

epochs made: 301.0


Create dummy dataset

In [11]:
import fibonacci_utilities as fib
import render

In [12]:
azimuths, elevations = fib.fibonacci_azimuths_and_elevations(15)

In [ ]:
data = np.load('/home/gzanin/Desktop/classroomBase/RIRs.npy', allow_pickle=True, encoding= 'latin1')
data.shape

In [20]:
##########only 12 microphones are considered

m = []

for i in range (12):
    m.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(m)):
    for r in m[j]:
        r['t_response'] = data[j]

m = np.array(m)

In [23]:
#m = data[:12]

In [ ]:
m.shape

In [24]:
np.save('/home/gzanin/Desktop/prova_dataset/RIRs.npy', m)

In [ ]:
new_data = np.load('/home/gzanin/Desktop/prova_dataset/xyzs.npy', allow_pickle=True, encoding= 'latin1')

new_data
