In [22]:
import numpy as np
import torch

In [36]:
#data = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', allow_pickle = True)

data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_different/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']


OrderedDict([('energy_vector',
              tensor([[[ 0.2358, -0.3700,  1.2930, -0.3559, -0.5278, -0.4747, -1.1789,
                        -2.0230, -1.1184, -1.3833],
                       [-0.2358,  0.3700, -1.2930,  0.3559,  0.5278,  0.4747,  1.1789,
                         2.0230,  1.1184,  1.3833]],
              
                      [[-1.1596, -0.4881, -0.3753, -1.7862,  0.4012, -1.7094, -1.6006,
                        -2.0352,  0.8716,  1.9510],
                       [ 1.1596,  0.4881,  0.3753,  1.7862, -0.4012,  1.7094,  1.6006,
                         2.0352, -0.8716, -1.9510]],
              
                      [[-2.4367, -1.0749, -1.5681, -0.6310, -0.5543, -1.6173, -0.8984,
                        -1.0310, -2.3357, -1.9602],
                       [ 2.4367,  1.0749,  1.5681,  0.6310,  0.5543,  1.6173,  0.8984,
                         1.0310,  2.3357,  1.9602]],
              
                      [[-1.6467, -0.4605, -1.1996, -1.1455, -1.5221, -0.6231, -1.6541,


In [37]:
np.average(data['model_state_dict']['RIR_residual']**2)

3.3706185e-06

In [23]:
data = torch.load('C:/Users/giova/Documents/Units/IIT/hearinganythinganywhere/~/espoo_s2_200om+300om_epochs/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']

OrderedDict([('energy_vector',
              tensor([[[-0.4306,  0.0139, -0.1534, -0.6002, -0.5568, -0.8848, -0.6152,
                        -0.5500, -0.4947, -1.0771],
                       [ 0.4306, -0.0139,  0.1534,  0.6002,  0.5568,  0.8848,  0.6152,
                         0.5500,  0.4947,  1.0771]],
              
                      [[-0.5032, -0.3979, -0.6826, -0.8591, -0.6661, -0.7019, -0.4719,
                        -0.4146, -0.3564, -1.1106],
                       [ 0.5032,  0.3979,  0.6826,  0.8591,  0.6661,  0.7019,  0.4719,
                         0.4146,  0.3564,  1.1106]],
              
                      [[-0.6106, -0.3106,  0.5309, -0.9772, -1.1807, -1.0646, -1.1549,
                        -1.1210, -1.0190, -1.1071],
                       [ 0.6106,  0.3106, -0.5309,  0.9772,  1.1807,  1.0646,  1.1549,
                         1.1210,  1.0190,  1.1071]],
              
                      [[-0.7347, -0.5260, -1.3325, -1.1374, -1.1475, -0.9857, -1.1167,


In [39]:
np.average(data['model_state_dict']['RIR_residual']**2)

1.4959952e-06

In [ ]:
data['model_state_dict']['spline_values']

In [ ]:
model_weights = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/hallwayBase/weights.pt', map_location=torch.device('cpu'))

#print(model_weights.keys())

In [ ]:
model_weights['model_state_dict']['spline_values']

In [20]:
data_losses = np.load('C:/Users/giova/Documents/Units/IIT/hearinganythinganywhere/~/espoo_s2_200amb+300om_epochs/losses.npy')
data_losses.shape

print("epochs made:", data_losses.shape[0]/7)

epochs made: 200.0


Create dummy dataset

In [ ]:
import fibonacci_utilities as fib
import render

In [ ]:
azimuths, elevations = fib.fibonacci_azimuths_and_elevations(15)

In [5]:
data = np.load('/home/gzanin/Desktop/classroomBase/RIRs.npy', allow_pickle=True, encoding= 'latin1')
data

array([[ 6.11514818e-06,  7.35741694e-06,  5.00817302e-06, ...,
        -7.26507135e-07,  3.53323294e-07,  5.90716509e-07],
       [ 9.97966657e-06,  3.15541092e-05, -1.79595778e-06, ...,
         2.03789893e-06, -1.19009891e-05, -3.57242990e-06],
       [ 9.85353793e-06,  7.06042298e-06,  1.01186370e-05, ...,
        -1.48643564e-06,  1.73800477e-06, -1.97854981e-06],
       ...,
       [ 1.95844156e-05,  2.08539409e-05,  2.17284163e-05, ...,
         1.87933942e-05,  2.10904654e-05,  1.78315590e-05],
       [ 8.10003875e-06,  9.77486737e-06,  8.16097347e-06, ...,
         7.35602554e-07, -3.14799097e-07,  1.75372285e-06],
       [ 6.92069176e-06,  6.67534747e-06,  5.70008310e-06, ...,
        -1.09548276e-06,  4.15361797e-06,  1.40834412e-07]])

In [ ]:
##########only 12 microphones are considered

m = []

for i in range (12):
    m.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(m)):
    for r in m[j]:
        r['t_response'] = data[j]

m = np.array(m)

In [ ]:
#m = data[:12]

In [ ]:
m.shape

In [ ]:
np.save('/home/gzanin/Desktop/prova_dataset/RIRs.npy', m)

In [10]:
new_data = np.load("../classroomBase/xyzs.npy")

new_data


array([[2.4241125 , 0.581025  , 0.32      ],
       [2.16535   , 0.581025  , 0.32      ],
       [1.90738125, 0.581025  , 0.32      ],
       ...,
       [5.04586875, 7.648575  , 1.5113    ],
       [4.78393125, 7.648575  , 1.5113    ],
       [4.524375  , 7.648575  , 1.5113    ]])

In [11]:
nottingham1_positions = np.array([[6.68, 6.07, 0.55], [6.60, 1.42, 0.55], [1.50, 1.39, 0.55], [1.35, 5.95, 0.55], [6.68, 6.07, 2.00], [6.60, 1.42, 2.00], [1.50, 1.39, 2.00], [1.35, 5.95, 2.00], [5.28, 6.04, 1.40], [2.86, 6.01, 1.40]])

In [12]:
np.save('../Nottingham1/xyzs.npy', nottingham1_positions)

In [2]:
nottingham2_positions = np.array([[4.04, 5.60, 1.45], [4.04, 5.60, 1.45], [4.04, 5.60, 1.45], [4.04, 5.60, 1.45], [4.10, 5.80, 1.60]])

In [4]:
np.save('../Nottingham2/xyzs.npy', nottingham2_positions)

In [5]:
nottingham3_positions = np.array([[3.51, 4.00, 1.80]])

In [6]:
np.save('../Nottingham3/xyzs.npy', nottingham3_positions)