In [1]:
import numpy as np
import torch

In [2]:
#data = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', allow_pickle = True)

data = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/weights.pt', map_location=torch.device('cpu'))
data['model_state_dict']


OrderedDict([('energy_vector',
              tensor([[[-1.2105, -0.6898, -0.7542, -1.1262, -0.4720, -0.3523, -0.8585,
                        -0.9232, -0.5353, -1.0581],
                       [ 1.2105,  0.6898,  0.7542,  1.1262,  0.4720,  0.3523,  0.8585,
                         0.9232,  0.5353,  1.0581]],
              
                      [[-0.8692, -0.5684, -1.0809, -1.0215, -0.4124, -1.0143, -0.6256,
                        -0.4943, -0.6451, -1.1420],
                       [ 0.8692,  0.5684,  1.0809,  1.0215,  0.4124,  1.0143,  0.6256,
                         0.4943,  0.6451,  1.1420]],
              
                      [[-1.6262, -1.2395, -1.3932, -1.0594, -1.4244, -0.3195, -0.5973,
                        -0.6629, -0.0424, -0.5722],
                       [ 1.6262,  1.2395,  1.3932,  1.0594,  1.4244,  0.3195,  0.5973,
                         0.6629,  0.0424,  0.5722]],
              
                      [[-1.4128, -0.8613, -1.0688, -1.8623, -1.6768, -0.6424, -1.0768,


In [3]:
data['model_state_dict']['spline_values']

tensor([-2.3781, -1.8732, -2.2199, -0.9309, -0.7883, -0.8614, -1.3513, -2.3236,
        -1.6415, -2.3728, -1.7739, -1.3295,  0.1876,  1.0328,  1.9185,  2.2384,
         2.4763,  2.9482,  0.8513,  2.8332,  3.4219,  3.6815,  3.8908,  3.9024,
         3.6092,  4.6633,  4.9367,  2.6658,  3.4229,  3.7009,  4.2821,  3.8060,
         3.8174,  4.0510])

In [5]:
model_weights = torch.load('/home/gzanin/Desktop/hearinganythinganywhere/models/hallwayBase/weights.pt', map_location=torch.device('cpu'))

#print(model_weights.keys())

In [6]:
model_weights['model_state_dict']['spline_values']

tensor([-1.1889,  0.9600,  0.1497, -1.6674, -1.7362, -0.8662, -0.0920, -0.1603,
        -0.7774, -0.5799, -0.2962, -0.4480, -0.3558, -0.4179, -0.6262, -0.7645,
        -0.8553, -0.9175, -1.0549, -1.1494, -1.2660, -1.3254, -1.3975, -1.4152,
        -1.5259, -1.5676, -1.6296, -1.7462, -1.7349, -1.8844, -2.0238, -2.2500,
        -2.5868, -2.5822])

In [8]:
data_losses = np.load('/home/gzanin/Desktop/hearinganythinganywhere/~/prova_training_1000epochs/losses.npy')
data_losses.shape

print("epochs made:", data_losses.shape[0]/8)

epochs made: 156.0


Create dummy dataset

In [11]:
import fibonacci_utilities as fib
import render

In [5]:
def initialize_directional_list_for_beampattern(angular_sensitivity, n_freq_samples, device):

    frequency_responses_list = []
    used_angle = 180/(int(180/angular_sensitivity))
    azimuths = np.arange(0, 360, used_angle)
    elevations = np.arange(-90, 90+ used_angle, used_angle)
    for elevation in elevations:
        if (elevation == -90 or elevation == 90):
            direction_dict = dict()
            direction_dict['angle'] = [0, elevation]#-90 and +90 elevations are considered having azimuth=0
            direction_dict['f_response'] = torch.zeros(n_freq_samples).to(device)
            frequency_responses_list.append(direction_dict)
        else:   
            for azimuth in azimuths:
                direction_dict = dict()
                direction_dict['angle'] = [azimuth, elevation]
                direction_dict['f_response'] = torch.zeros(n_freq_samples).to(device)
                frequency_responses_list.append(direction_dict)

    return frequency_responses_list

In [12]:
azimuths, elevations = fib.fibonacci_azimuths_and_elevations(15)

In [ ]:
data = np.load('/home/gzanin/Desktop/classroomBase/RIRs.npy', allow_pickle=True, encoding= 'latin1')
data.shape

In [20]:
##########only 12 microphones are considered

m = []

for i in range (12):
    m.append(render.initialize_directional_list(azimuths, elevations, 1, "cpu"))

for j in range (len(m)):
    for r in m[j]:
        r['t_response'] = data[j]

m = np.array(m)

In [23]:
#m = data[:12]

In [ ]:
m.shape

In [24]:
np.save('/home/gzanin/Desktop/prova_dataset/RIRs.npy', m)

In [ ]:
new_data = np.load('/home/gzanin/Desktop/prova_dataset/xyzs.npy', allow_pickle=True, encoding= 'latin1')

new_data
