In [1]:
%load_ext autoreload
%autoreload 2
import open3d as o3d
import surface_creation_utilities as S
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:

pcd = o3d.io.read_point_cloud('../nottingham_pc.ply')

In [3]:
#d = o3d.data.LivingRoomPointClouds()
#pcd = o3d.io.read_point_cloud(d.paths[9])
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')

pcd = o3d.io.read_point_cloud('../nottingham_pc.ply')
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))



base_surfaces = S.get_surfaces_from_point_cloud(pcd)
print("base surfaces")
for surface in base_surfaces:
    print (surface.points, surface.parallelogram, surface.n)

base surfaces
[[-0.73818969 -1.20614918 -0.41641597]
 [-2.56295085 -1.25942851 -0.3183701 ]
 [-0.87020855 -1.20353181 -2.87203627]] True [ 0.02904441 -0.99957467 -0.0026269 ]
[[-4.18170014 -1.56378021 -0.57853648]
 [-4.18630239 -1.56267781 -2.96765868]
 [-0.89132741 -1.638165   -0.58490916]] True [-2.26018288e-02 -9.99744459e-01 -4.17767532e-04]
[[ 3.27010914  9.41430621 -0.33447536]
 [ 5.75825159  9.50388153 -0.23717986]
 [ 3.36955511  9.37002953 -2.8368487 ]] True [-0.0352259   0.99919723 -0.01907957]
[[-2.12149354 -1.17993118 -2.98362238]
 [-2.01286697 -1.1763511  -0.43017903]
 [-6.13375611 -1.25206931 -2.81283473]] True [ 1.80035639e-02 -9.99837720e-01  6.35942032e-04]
[[-5.2709583  -3.74103023 -2.9874289 ]
 [-4.11651852 -2.50368408 -2.92875931]
 [-5.34653244 -3.78658161 -0.53967671]] True [ 0.73090904 -0.68240355  0.00986758]
[[ 3.10632146 -3.46812128 -2.19564985]
 [ 4.48033593 -3.29873949 -2.19554447]
 [ 2.84410287 -1.34102061 -2.19541588]] True [-6.21855584e-05 -1.17659498e-04  

In [4]:
'''
optimized_surfaces = S.get_surfaces_from_point_cloud_with_optimization(pcd, cut_impurity= 0.20, steps_per_side=2)
print("optimized surfaces", optimized_surfaces)
for surface in optimized_surfaces:
    print (surface.points, surface.parallelogram, surface.n)
    '''

'\noptimized_surfaces = S.get_surfaces_from_point_cloud_with_optimization(pcd, cut_impurity= 0.20, steps_per_side=2)\nprint("optimized surfaces", optimized_surfaces)\nfor surface in optimized_surfaces:\n    print (surface.points, surface.parallelogram, surface.n)\n    '

In [5]:
import trace1 as G
import plotly.graph_objects as go

fig = go.Figure()
#pcd = o3d.io.read_point_cloud(d.paths[9])
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)#############################################
G.plot_surfaces(fig, base_surfaces)


In [ ]:
'''
detected_planes = pcd.detect_planar_patches(normal_variance_threshold_deg=70, coplanarity_deg=75, outlier_ratio=0.75, min_plane_edge_length=0.0, min_num_points=0, search_param=o3d.geometry.KDTreeSearchParamKNN(knn=20)) #si potrebbe fare fine tuning

for i in range (len(detected_planes)):  
    oobb = detected_planes[i]
    mesh = oobb.get_box_points()  # Crea i vertici del box
    oobb_mesh = o3d.geometry.TriangleMesh.create_from_oriented_bounding_box(oobb)
    o3d.io.write_triangle_mesh("../planes_nottingham/bounding_box_" + str(i) + ".ply", oobb_mesh)
'''

Optimized surfaces with 2 cuts and 0.2 impurity

In [ ]:
'''
fig = go.Figure()
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)
G.plot_surfaces(fig, optimized_surfaces)
'''


optimized surfaces with 5 cuts and 0.2 impurity(ran on cluster)

In [ ]:
'''
import trace1 as G
import plotly.graph_objects as go
import numpy as np

s1 = G.Surface(np.array([np.array([-10.09956508,   3.65454533,  -7.84540534]),np.array([  0.86774405,   6.99933054,   6.01149353]), np.array([ 10.98616466,   3.66615976,  -8.4795603 ])]), False)
s2 = G.Surface (np.array([np.array([ 7.55907675,  4.35202429, -7.91548223]), np.array([ 2.70740392, -0.89751088, -7.98298702]), np.array([-7.380409,    3.92225067, -7.09470918])]), True)
s3 = G.Surface(np.array([np.array([-11.56846834,   4.45404118,  -7.36522756]), np.array([-11.68461323,  -1.04622091,  -3.9365148 ]), np.array([-11.16990109,   4.68593711,   2.4972895 ])]), True )
s4 = G.Surface(np.array([np.array([  9.46738246,  -1.46172153,   4.32533956]), np.array([  4.22134378,   7.33461314,   5.36916622]), np.array([-11.38545785,  -1.66056523,   6.16671428])]), False)
s5 = G.Surface(np.array([np.array([ 7.83008668, -0.86969988,  3.93674075]), np.array([ 7.62700772,  4.06404333,  2.11977209]), np.array([ 7.84355217, -0.99216121, -1.15348157])]), True)
s6 = G.Surface(np.array([np.array([11.1342835,  -0.08410565, -8.7524018 ]), np.array([ 5.79069151, -0.5683638,   5.59693664]), np.array([-6.39798901, -1.12114865, -8.14225057])]), True)


well_optimized_surfaces = [s1, s2, s3, s4, s5, s6]
'''

In [ ]:
'''
fig = go.Figure()
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)
G.plot_surfaces(fig, well_optimized_surfaces)
'''

Limerick planes 

In [ ]:
'''
limerick_planes = o3d.io.read_point_cloud('/home/gzanin/Documents/limerick_planes.ply')
fig = go.Figure()
G.plot_points(fig, np.array(limerick_planes.points), size=0.3)
'''

[Open3D WARNING] Read PLY failed: unable to parse header.


RPly: Wrong magic number. Expected 'ply'
