In [326]:
%load_ext autoreload
%autoreload 2
import open3d as o3d
import surface_creation_utilities as S
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [327]:

pcd = o3d.io.read_point_cloud('../nottingham_pc.ply')

In [328]:
#d = o3d.data.LivingRoomPointClouds()
#pcd = o3d.io.read_point_cloud(d.paths[9])
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')

pcd = o3d.io.read_point_cloud('../nottingham_pc.ply')
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))



base_surfaces = S.get_surfaces_from_point_cloud(pcd)
print("base surfaces")
for surface in base_surfaces:
    print (surface.points, surface.parallelogram, surface.n)

base surfaces
[[-0.73818969 -1.20614918 -0.41641597]
 [-2.56295085 -1.25942851 -0.3183701 ]
 [-0.87020855 -1.20353181 -2.87203627]] True [ 0.02904441 -0.99957467 -0.0026269 ]
[[-4.18170014 -1.56378021 -0.57853648]
 [-4.18630239 -1.56267781 -2.96765868]
 [-0.89132741 -1.638165   -0.58490916]] True [-2.26018288e-02 -9.99744459e-01 -4.17767532e-04]
[[ 3.27010914  9.41430621 -0.33447536]
 [ 5.75825159  9.50388153 -0.23717986]
 [ 3.36955511  9.37002953 -2.8368487 ]] True [-0.0352259   0.99919723 -0.01907957]
[[-2.12149354 -1.17993118 -2.98362238]
 [-2.01286697 -1.1763511  -0.43017903]
 [-6.13375611 -1.25206931 -2.81283473]] True [ 1.80035639e-02 -9.99837720e-01  6.35942032e-04]
[[-5.2709583  -3.74103023 -2.9874289 ]
 [-4.11651852 -2.50368408 -2.92875931]
 [-5.34653244 -3.78658161 -0.53967671]] True [ 0.73090904 -0.68240355  0.00986758]
[[ 3.10632146 -3.46812128 -2.19564985]
 [ 4.48033593 -3.29873949 -2.19554447]
 [ 2.84410287 -1.34102061 -2.19541588]] True [-6.21855584e-05 -1.17659498e-04  

In [329]:
'''
optimized_surfaces = S.get_surfaces_from_point_cloud_with_optimization(pcd, cut_impurity= 0.20, steps_per_side=2)
print("optimized surfaces", optimized_surfaces)
for surface in optimized_surfaces:
    print (surface.points, surface.parallelogram, surface.n)
    '''

'\noptimized_surfaces = S.get_surfaces_from_point_cloud_with_optimization(pcd, cut_impurity= 0.20, steps_per_side=2)\nprint("optimized surfaces", optimized_surfaces)\nfor surface in optimized_surfaces:\n    print (surface.points, surface.parallelogram, surface.n)\n    '

In [330]:
for i in range(len(base_surfaces)):
    print("surface ", i)
    print(base_surfaces[i].points)

surface  0
[[-0.73818969 -1.20614918 -0.41641597]
 [-2.56295085 -1.25942851 -0.3183701 ]
 [-0.87020855 -1.20353181 -2.87203627]]
surface  1
[[-4.18170014 -1.56378021 -0.57853648]
 [-4.18630239 -1.56267781 -2.96765868]
 [-0.89132741 -1.638165   -0.58490916]]
surface  2
[[ 3.27010914  9.41430621 -0.33447536]
 [ 5.75825159  9.50388153 -0.23717986]
 [ 3.36955511  9.37002953 -2.8368487 ]]
surface  3
[[-2.12149354 -1.17993118 -2.98362238]
 [-2.01286697 -1.1763511  -0.43017903]
 [-6.13375611 -1.25206931 -2.81283473]]
surface  4
[[-5.2709583  -3.74103023 -2.9874289 ]
 [-4.11651852 -2.50368408 -2.92875931]
 [-5.34653244 -3.78658161 -0.53967671]]
surface  5
[[ 3.10632146 -3.46812128 -2.19564985]
 [ 4.48033593 -3.29873949 -2.19554447]
 [ 2.84410287 -1.34102061 -2.19541588]]
surface  6
[[-0.55093076 -6.24433132 -3.15053783]
 [-0.56700911 -6.31284051 -0.40148313]
 [-0.74029551 -0.657647   -3.0124196 ]]
surface  7
[[-6.01878314 -2.334387   -3.12963988]
 [-6.01331376 -2.46689625  2.22450854]
 [-6.313

In [331]:
import trace1 as G

new_surfaces = []
for surface in [base_surfaces[2]] + base_surfaces[7:]:
    
    new_surfaces.append(G.Surface(surface.points - [ 6.35398226, -7.2131221,  -2.8166089 ]- [-1.88644833e-09, -1.97645900e-09, -4.97628339e-09] - [11.80475204,   0.50874813,  -0.71329534]))

In [332]:
new_new_surfaces =[]

for surface in new_surfaces:
    
    new_new_surfaces.append(G.Surface(surface.points * [1,1,1] + [24,0,0]))
    
new_surfaces = new_new_surfaces

In [333]:
new_new_surfaces =[]

for surface in new_surfaces:
    p0 = np.array([surface.points[0][1], -1 * surface.points[0][0], surface.points[0][2]])
    p1 = np.array([surface.points[1][1], -1 * surface.points[1][0], surface.points[1][2]])
    p2 = np.array([surface.points[2][1], -1 * surface.points[2][0], surface.points[2][2]])
    
    new_new_surfaces.append(G.Surface([p0,p1,p2]))
    
new_surfaces = new_new_surfaces

In [334]:
new_surfaces[3] = G.Surface(np.array([[0,0,0], [0,0,6.76461222], [16.98386952,0,0]]))
new_surfaces = [new_surfaces[0]] + new_surfaces[2:]

In [335]:
for i in range(len(new_surfaces)):
    print("surface ", i)
    print(new_surfaces[i].points)

surface  0
[array([16.11868018, -9.11137484,  3.19542889]), array([ 16.2082555 , -11.59951729,   3.29272438]), array([16.0744035 , -9.21082081,  0.69305554])]
surface  1
[array([ 16.38804539, -11.85609575,   0.29981552]), array([ 16.53636718, -11.84236386,   6.37222734]), array([ -0.50874813, -12.19524796,   0.71329534])]
surface  2
[[ 0.          0.          0.        ]
 [ 0.          0.          6.76461222]
 [16.98386952  0.          0.        ]]
surface  3
[array([15.67651474,  0.8067807 ,  0.62069236]), array([15.7106522 ,  0.62599116,  6.76461222]), array([ 16.98386952, -11.69356421,   0.24559609])]
surface  4
[array([ -3.40656751, -12.17850029,   0.65563787]), array([-3.08419846,  1.05461696,  0.65817424]), array([ 16.36775567, -12.66021881,   0.65871967])]
surface  5
[array([ 5.74038483e-10, -3.90495920e-01, -8.49393555e-10]), array([-0.0226636 ,  0.0967916 ,  5.69084249]), array([  0.45904213, -12.74455183,   1.05966398])]


In [336]:
new_surfaces[5] = G.Surface(np.array([[0, 0, 0], [0, 0, 6.76461222], [0,-12.74455183,0]]))
new_surfaces[1] = G.Surface(np.array([[16.98386952,-12.74455183,0], [16.98386952,-12.74455183,6.76461222], [0,-12.74455183,0]]))
new_surfaces[3] = G.Surface(np.array([[16.98386952, 0, 0], [16.98386952, 0, 6.76461222], [16.98386952,-12.74455183,0]]))
new_surfaces[0] = G.Surface(np.array([[16.8, -9.1610978, 3.2440766], [16.8, -11.59951729, 3.2440766], [16.8,-9.1610978,0]]))
new_surfaces[4] = G.Surface(np.array([[-3.40656751, -12.74455183, 0], [-3.40656751, 1.05461696, 0], [16.98386952,-12.74455183,0]]))

In [337]:
import trace1 as G
import plotly.graph_objects as go

fig = go.Figure()
#pcd = o3d.io.read_point_cloud(d.paths[9])
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)#############################################
G.plot_surfaces(fig, new_surfaces)


In [338]:
#table
new_surfaces.append(G.Surface(np.array([[4.40, -6, 0.73], [6, -6, 0.73], [4.40,-6.80,0.73]])))

In [339]:
#tables
new_surfaces.append(G.Surface(np.array([[6.80, -1.30, 0.73], [6.80, -2.90, 0.73], [7.60,-1.30,0.73]])))
new_surfaces.append(G.Surface(np.array([[6.80, -3.90, 0.73], [6.80, -5.50, 0.73], [7.60,-3.90,0.73]])))

#monitor
new_surfaces.append(G.Surface(np.array([[6.85, -4.35, 0.90], [6.85, -5.05, 0.90], [6.85,-4.35,1.30]])))

In [340]:
#big panel on the wall
new_surfaces.append(G.Surface(np.array([[16.8, -4, 2], [16.8, -4, 4.50], [16.8,-8.50,2]])))

#green screen
new_surfaces.append(G.Surface(np.array([[16.98386952, 0, 0], [16.8, 0, 2.40], [16.8,-4.20,0]])))
new_surfaces.append(G.Surface(np.array([[16.98386952, 0, 0], [13.50, 0, 0], [16.98386952, 0, 2.40]])))

In [341]:
#ceiling
new_surfaces.append(G.Surface(np.array([[0, 0, 6.76461222], [0, -12.74455183, 6.76461222], [16.98386952,0,6.76461222]])))

In [342]:
#left wall doors
new_surfaces.append(G.Surface(np.array([[0, -0.30, 0], [0, -2.10, 0], [0,-0.30, 2]])))
new_surfaces.append(G.Surface(np.array([[0, -3.10, 0], [0, -5.60, 0], [0,-3.10, 2]])))
new_surfaces.append(G.Surface(np.array([[0, -7, 0], [0, -9, 0], [0,-7, 2]])))


In [343]:
len(new_surfaces)

17

In [344]:
import trace1 as G
import plotly.graph_objects as go

fig = go.Figure()
#pcd = o3d.io.read_point_cloud(d.paths[9])
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)#############################################
G.plot_surfaces(fig, new_surfaces)

In [345]:
'''
detected_planes = pcd.detect_planar_patches(normal_variance_threshold_deg=70, coplanarity_deg=75, outlier_ratio=0.75, min_plane_edge_length=0.0, min_num_points=0, search_param=o3d.geometry.KDTreeSearchParamKNN(knn=20)) #si potrebbe fare fine tuning

for i in range (len(detected_planes)):  
    oobb = detected_planes[i]
    mesh = oobb.get_box_points()  # Crea i vertici del box
    oobb_mesh = o3d.geometry.TriangleMesh.create_from_oriented_bounding_box(oobb)
    o3d.io.write_triangle_mesh("../planes_nottingham/bounding_box_" + str(i) + ".ply", oobb_mesh)
'''

'\ndetected_planes = pcd.detect_planar_patches(normal_variance_threshold_deg=70, coplanarity_deg=75, outlier_ratio=0.75, min_plane_edge_length=0.0, min_num_points=0, search_param=o3d.geometry.KDTreeSearchParamKNN(knn=20)) #si potrebbe fare fine tuning\n\nfor i in range (len(detected_planes)):  \n    oobb = detected_planes[i]\n    mesh = oobb.get_box_points()  # Crea i vertici del box\n    oobb_mesh = o3d.geometry.TriangleMesh.create_from_oriented_bounding_box(oobb)\n    o3d.io.write_triangle_mesh("../planes_nottingham/bounding_box_" + str(i) + ".ply", oobb_mesh)\n'

Optimized surfaces with 2 cuts and 0.2 impurity

In [346]:
'''
fig = go.Figure()
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)
G.plot_surfaces(fig, optimized_surfaces)
'''


"\nfig = go.Figure()\n#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')\n#G.plot_points(fig, np.array(pcd.points), size=0.3)\nG.plot_surfaces(fig, optimized_surfaces)\n"

optimized surfaces with 5 cuts and 0.2 impurity(ran on cluster)

In [347]:
'''
import trace1 as G
import plotly.graph_objects as go
import numpy as np

s1 = G.Surface(np.array([np.array([-10.09956508,   3.65454533,  -7.84540534]),np.array([  0.86774405,   6.99933054,   6.01149353]), np.array([ 10.98616466,   3.66615976,  -8.4795603 ])]), False)
s2 = G.Surface (np.array([np.array([ 7.55907675,  4.35202429, -7.91548223]), np.array([ 2.70740392, -0.89751088, -7.98298702]), np.array([-7.380409,    3.92225067, -7.09470918])]), True)
s3 = G.Surface(np.array([np.array([-11.56846834,   4.45404118,  -7.36522756]), np.array([-11.68461323,  -1.04622091,  -3.9365148 ]), np.array([-11.16990109,   4.68593711,   2.4972895 ])]), True )
s4 = G.Surface(np.array([np.array([  9.46738246,  -1.46172153,   4.32533956]), np.array([  4.22134378,   7.33461314,   5.36916622]), np.array([-11.38545785,  -1.66056523,   6.16671428])]), False)
s5 = G.Surface(np.array([np.array([ 7.83008668, -0.86969988,  3.93674075]), np.array([ 7.62700772,  4.06404333,  2.11977209]), np.array([ 7.84355217, -0.99216121, -1.15348157])]), True)
s6 = G.Surface(np.array([np.array([11.1342835,  -0.08410565, -8.7524018 ]), np.array([ 5.79069151, -0.5683638,   5.59693664]), np.array([-6.39798901, -1.12114865, -8.14225057])]), True)


well_optimized_surfaces = [s1, s2, s3, s4, s5, s6]
'''

'\nimport trace1 as G\nimport plotly.graph_objects as go\nimport numpy as np\n\ns1 = G.Surface(np.array([np.array([-10.09956508,   3.65454533,  -7.84540534]),np.array([  0.86774405,   6.99933054,   6.01149353]), np.array([ 10.98616466,   3.66615976,  -8.4795603 ])]), False)\ns2 = G.Surface (np.array([np.array([ 7.55907675,  4.35202429, -7.91548223]), np.array([ 2.70740392, -0.89751088, -7.98298702]), np.array([-7.380409,    3.92225067, -7.09470918])]), True)\ns3 = G.Surface(np.array([np.array([-11.56846834,   4.45404118,  -7.36522756]), np.array([-11.68461323,  -1.04622091,  -3.9365148 ]), np.array([-11.16990109,   4.68593711,   2.4972895 ])]), True )\ns4 = G.Surface(np.array([np.array([  9.46738246,  -1.46172153,   4.32533956]), np.array([  4.22134378,   7.33461314,   5.36916622]), np.array([-11.38545785,  -1.66056523,   6.16671428])]), False)\ns5 = G.Surface(np.array([np.array([ 7.83008668, -0.86969988,  3.93674075]), np.array([ 7.62700772,  4.06404333,  2.11977209]), np.array([ 7.84

In [348]:
'''
fig = go.Figure()
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)
G.plot_surfaces(fig, well_optimized_surfaces)
'''

"\nfig = go.Figure()\n#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')\n#G.plot_points(fig, np.array(pcd.points), size=0.3)\nG.plot_surfaces(fig, well_optimized_surfaces)\n"

Limerick planes 

In [349]:
'''
limerick_planes = o3d.io.read_point_cloud('/home/gzanin/Documents/limerick_planes.ply')
fig = go.Figure()
G.plot_points(fig, np.array(limerick_planes.points), size=0.3)
'''

"\nlimerick_planes = o3d.io.read_point_cloud('/home/gzanin/Documents/limerick_planes.ply')\nfig = go.Figure()\nG.plot_points(fig, np.array(limerick_planes.points), size=0.3)\n"