In [16]:
%load_ext autoreload
%autoreload 2
import open3d as o3d
import surface_creation_utilities as S

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [1]:
#d = o3d.data.LivingRoomPointClouds()
#pcd = o3d.io.read_point_cloud(d.paths[9])
pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))



base_surfaces = S.get_surfaces_from_point_cloud(pcd)
print("base surfaces")
for surface in base_surfaces:
    print (surface.points, surface.parallelogram, surface.n)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
base surfaces
[[ -9.67512082   6.99352332   6.32857101]
 [-10.09956508   3.65454533  -7.84540534]
 [ 11.41060892   7.00513775   5.69441605]] True [ 0.00742569 -0.97337981  0.22907771]
[[  7.6872325   -0.754253    -8.25657803]
 [  7.55907675   4.35202429  -7.91548223]
 [-12.23208183  -1.3272845   -7.16221397]] True [ 0.05660853 -0.0651294   0.99626986]
[[-11.81746898  -1.12351956  -7.22402049]
 [-11.56846834   4.45404118  -7.36522756]
 [-11.28604598  -0.81432499   5.92600225]] True [ 0.99818967 -0.04555661 -0.039268  ]
[[  9.46738246  -1.46172153   4.32533956]
 [  9.43455386   7.38432406   4.90882254]
 [-11.38545785  -1.66056523   6.16671428]] True [ 0.08839088 -0.06523251  0.99394757]
[[ 7.62251922  4.10486377  3.81651286]
 [ 7.83008668 -0.86969988  3.93674075]
 [ 7.64047322  3.941582   -2.97045023]] True [0.99912762 0.

In [2]:
optimized_surfaces = S.get_surfaces_from_point_cloud_with_optimization(pcd, cut_impurity= 0.20, steps_per_side=2)
print("optimized surfaces", optimized_surfaces)
for surface in optimized_surfaces:
    print (surface.points, surface.parallelogram, surface.n)

OrientedBoundingBox: center: (0.655522, 5.32984, -1.07549), extent: 14.5681, 21.0953, 0.762579)
let's try the triangles
trying cut 0.0
trying cut 1.0
let's try with parallelograms
trying cut 0.0
trying type 1
trying type 2
trying type 3
trying type 4
trying cut 1.0
trying type 1
trying type 2
trying type 3
trying type 4
OrientedBoundingBox: center: (-2.3365, 1.51237, -7.53885), extent: 5.11926, 19.9576, 0.355377)
let's try the triangles
trying cut 0.0
trying cut 1.0
let's try with parallelograms
trying cut 0.0
trying type 1
trying type 2
trying type 3
trying type 4
trying cut 1.0
trying type 1
trying type 2
trying type 3
trying type 4
OrientedBoundingBox: center: (-11.4273, 1.81986, -0.719613), extent: 5.5849, 13.1644, 0.296239)
let's try the triangles
trying cut 0.0
trying cut 1.0
let's try with parallelograms
trying cut 0.0
trying type 1
trying type 2
trying type 3
trying type 4
trying cut 1.0
trying type 1
trying type 2
trying type 3
trying type 4
OrientedBoundingBox: center: (-0.97

In [3]:
import trace1 as G
import plotly.graph_objects as go

fig = go.Figure()
#pcd = o3d.io.read_point_cloud(d.paths[9])
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)#############################################
G.plot_surfaces(fig, base_surfaces)


Optimized surfaces with 2 cuts and 0.2 impurity

In [4]:
fig = go.Figure()
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)
G.plot_surfaces(fig, optimized_surfaces)


optimized surfaces with 5 cuts and 0.2 impurity(ran on cluster)

In [13]:
import trace1 as G
import plotly.graph_objects as go
import numpy as np

s1 = G.Surface(np.array([np.array([-10.09956508,   3.65454533,  -7.84540534]),np.array([  0.86774405,   6.99933054,   6.01149353]), np.array([ 10.98616466,   3.66615976,  -8.4795603 ])]), False)
s2 = G.Surface (np.array([np.array([ 7.55907675,  4.35202429, -7.91548223]), np.array([ 2.70740392, -0.89751088, -7.98298702]), np.array([-7.380409,    3.92225067, -7.09470918])]), True)
s3 = G.Surface(np.array([np.array([-11.56846834,   4.45404118,  -7.36522756]), np.array([-11.68461323,  -1.04622091,  -3.9365148 ]), np.array([-11.16990109,   4.68593711,   2.4972895 ])]), True )
s4 = G.Surface(np.array([np.array([  9.46738246,  -1.46172153,   4.32533956]), np.array([  4.22134378,   7.33461314,   5.36916622]), np.array([-11.38545785,  -1.66056523,   6.16671428])]), False)
s5 = G.Surface(np.array([np.array([ 7.83008668, -0.86969988,  3.93674075]), np.array([ 7.62700772,  4.06404333,  2.11977209]), np.array([ 7.84355217, -0.99216121, -1.15348157])]), True)
s6 = G.Surface(np.array([np.array([11.1342835,  -0.08410565, -8.7524018 ]), np.array([ 5.79069151, -0.5683638,   5.59693664]), np.array([-6.39798901, -1.12114865, -8.14225057])]), True)


well_optimized_surfaces = [s1, s2, s3, s4, s5, s6]

In [14]:
fig = go.Figure()
#pcd = o3d.io.read_point_cloud('../limerick_pc.ply')
#G.plot_points(fig, np.array(pcd.points), size=0.3)
G.plot_surfaces(fig, well_optimized_surfaces)

Limerick planes 

In [20]:
limerick_planes = o3d.io.read_point_cloud('/home/gzanin/Documents/limerick_planes.ply')
fig = go.Figure()
G.plot_points(fig, np.array(limerick_planes.points), size=0.3)

[Open3D WARNING] Read PLY failed: unable to parse header.


RPly: Wrong magic number. Expected 'ply'
